### ISSUE TITLE
The preprocess is missing some imports....

### ISSUE THREAD

**Issue by user1234554321** [CCareaga/attention_guided_cropping#1]
Some imports like argparse and torcvision.transforms (i assume this is what is used for transforms) are missing. Also, I wrote one using multiprocessing as the preprocess was taking lot of time....
[parallel_preprocess.txt](https://github.com/CCareaga/attention_guided_cropping/files/5044953/parallel_preprocess.txt)
It does not have progress bar, but one can ascertain the number of processed by counting the lines in output file (using wc -l)

**Comment by CCareaga** [comment]
Yeah I copied the code from my actual working directory, so I'm not surprised it doesn't work right out of the box... If you could make a pull request that would be awesome!
